[package]
name = "BCC_freq_spider"
version = "0.1.0"
authors = ["Garth <g-art-h@outlook.com>"]
edition = "2021"

[dependencies]
reqwest = "0.12.5"
tokio = { version = "1.39.1", features = ["rt", "rt-multi-thread", "macros"] }
regex = "1.10.5"

[profile.release]
debug = false
lto = true
